name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Build APK with Buildozer
      uses: digreatbrian/buildozer-action@v2
      with:
        command: echo "y" | buildozer android debug

    - name: Upload full build log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: full-build-log
        path: .buildozer/logs/

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: myapp
        path: ./bin/*.apk
